import { Animal, AnimalData } from "../types/animal";

// Datos quemados simulando respuesta de API
const ANIMALES: Animal[] = [
  {
    id: 1,
    name: "Maximiliano",
    type: "Perro",
    state: "Urgente",
    tag: "Sociable",
    age: "Adulto",
    description:
      "Tranquila y mimosa, busca un hogar donde pueda recibir mucho amor.",
    image: "/patitas-unidas/assets/patita_1.jpg",
    fundacionId: 1,
  },
  {
    id: 10,
    name: "Antonia",
    type: "Gato",
    state: "Urgente",
    tag: "Juguetón",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_10.jpg",
    fundacionId: 2,
  },
  {
    id: 2,
    name: "Sasha",
    type: "Perro",
    state: "Nuevo",
    tag: "Juguetón",
    age: "Cachorro",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_2.jpg",
    fundacionId: 1,
  },
  {
    id: 3,
    name: "Drax",
    type: "Perro",
    state: "Urgente",
    tag: "Tranquilo",
    age: "Cachorro",
    description:
      "Tranquila y mimosa, busca un hogar donde pueda recibir mucho amor.",
    image: "/patitas-unidas/assets/patita_3.jpg",
    fundacionId: 3,
  },
  {
    id: 4,
    name: "Tobhias",
    type: "Perro",
    state: "Urgente",
    tag: "Tranquilo",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_4.jpg",
    fundacionId: 1,
  },
  {
    id: 5,
    name: "Blanca nieves",
    type: "Gato",
    state: "Nuevo",
    tag: "Independiente",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_5.jpg",
    fundacionId: 2,
  },
  {
    id: 7,
    name: "Nina",
    type: "Gato",
    state: "Tranquilo",
    age: "Cachorro",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_7.jpg",
    fundacionId: 3,
  },
  {
    id: 8,
    name: "Blue",
    type: "Gato",
    state: "Juguetón",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_8.jpg",
    fundacionId: 2,
  },
  {
    id: 9,
    name: "Pelusa",
    type: "Perro",
    state: "Urgente",
    tag: "Juguetón",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_9.jpg",
    fundacionId: 1,
  },
  {
    id: 6,
    name: "Francheska",
    type: "Gato",
    state: "Urgente",
    tag: "Independiente",
    age: "Cachorro",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_6.jpg",
    fundacionId: 3,
  },
  {
    id: 122,
    name: "Tyson",
    type: "Perro",
    state: "No adopción",
    tag: "Lindo",
    age: "Adulto",
    description:
      "Perro lindo y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/tyson.jpg",
    fundacionId: 2,
  },
];

const ANIMALES_APADRINAMIENTO: Animal[] = [
  {
    id: 101,
    name: "Luna",
    type: "Gato",
    age: "Adulto",
    description: "Requiere cirugía y cuidados post-operatorios.",
    image: "/assets/patita_apadrina_1.jpg",
    state: "Necesita ayuda",
    tag: "Especial",
  },
  {
    id: 102,
    name: "Max",
    type: "Perro",
    age: "Cachorro",
    description: "Necesita tratamiento médico y alimentación especial.",
    image: "/assets/patita_apadrina_2.jpg",
    state: "Necesita ayuda",
    tag: "Tratamiento",
  },
  {
    id: 103,
    name: "Milo",
    type: "Gato",
    age: "Adulto",
    description: "Requiere medicación diaria para su recuperación.",
    image: "/assets/patita_apadrina_3.jpg",
    state: "Necesita ayuda",
    tag: "Medicamentos",
  },
  {
    id: 104,
    name: "Nina",
    type: "Perro",
    age: "Cachorro",
    description: "Recuperándose de una fractura, necesita fisioterapia.",
    image: "/assets/patita_apadrina_4.jpg",
    state: "Necesita ayuda",
    tag: "Fisioterapia",
  },
];

const AnimalsData: AnimalData[] = [
  {
    id: 1,
    name: "Maximiliano",
    type: "Perro",
    state: "Urgente",
    tag: "Sociable",
    age: "Adulto",
    description:
      "Tranquila y mimosa, busca un hogar donde pueda recibir mucho amor.",
    image: "/patitas-unidas/assets/patita_1.jpg",
    fundacionId: 1,
    breed: "Mestizo",
    gender: "Macho",
    size: "Mediano",
    color: "Marrón y blanco",
    personality: ["Cariñoso", "Sociable", "Tranquilo", "Leal"],
    healthStatus: "Bueno",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Perros", "Niños", "Adultos"],
    notGoodWith: ["Gatos"],
    adoptionRequirements: [
      "Hogar con espacio adecuado",
      "Compromiso de seguimiento veterinario",
      "Visita previa al hogar",
    ],
    story:
      "Maximiliano fue encontrado abandonado en un parque cuando apenas tenía 2 años. Estaba desnutrido y asustado. Un rescatista lo llevó a su casa, donde recibió atención veterinaria y mucho amor. Ahora está completamente recuperado y listo para encontrar un hogar definitivo donde pueda dar todo su amor.",
    images: [
      "/patitas-unidas/assets/patita_1.jpg",
    ],
    createdAt: "2023-05-15",
    foundation: {
      id: 1,
      name: "Huellitas de Amor",
      logo: "/patitas-unidas/assets/huellitas_logo.jpg",
      city: "Bogotá",
      description:
        "Rescatamos y damos en adopción animales en situación de calle en Bogotá.",
      email: "contacto@huellitasdeamor.org",
      phone: "+57 300 123 4567",
    },
  },
  {
    id: 10,
    name: "Antonia",
    type: "Gato",
    state: "Urgente",
    tag: "Juguetón",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_10.jpg",
    fundacionId: 2,
    breed: "Siamés mezclado",
    gender: "Hembra",
    size: "Pequeño",
    color: "Gris y blanco",
    personality: ["Juguetona", "Curiosa", "Activa", "Independiente"],
    healthStatus: "Excelente",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Gatos", "Adultos"],
    notGoodWith: ["Perros grandes", "Niños pequeños"],
    adoptionRequirements: [
      "Hogar tranquilo",
      "Experiencia con gatos",
      "Compromiso de mantenerla como gato de interior",
    ],
    story:
      "Antonia fue rescatada de la calle junto con sus hermanos cuando apenas tenían unas semanas de vida. Es la más juguetona de la camada y ha crecido siendo una gata muy sociable con otros felinos. Busca un hogar donde pueda tener espacio para jugar y explorar.",
    images: [
      "/patitas-unidas/assets/patita_10.jpg",
      "/patitas-unidas/assets/patita_10.jpg",
      "/patitas-unidas/assets/patita_10.jpg",
    ],
    createdAt: "2023-08-10",
    foundation: {
      id: 2,
      name: "Patitas Felices",
      logo: "/patitas-unidas/assets/patitas_felices_logo.jpg",
      city: "Medellín",
      description:
        "Fundación dedicada al rescate y rehabilitación de gatos callejeros en Medellín.",
      email: "info@patitasfelices.org",
      phone: "+57 311 456 7890",
    },
  },
  {
    id: 2,
    name: "Sasha",
    type: "Perro",
    state: "Nuevo",
    tag: "Juguetón",
    age: "Cachorro",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_2.jpg",
    fundacionId: 1,
    breed: "Labrador mezclado",
    gender: "Hembra",
    size: "Mediano (en crecimiento)",
    color: "Dorado",
    personality: ["Juguetona", "Enérgica", "Cariñosa", "Curiosa"],
    healthStatus: "Excelente",
    vaccinated: true,
    sterilized: false,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Perros", "Gatos", "Niños", "Adultos"],
    notGoodWith: [],
    adoptionRequirements: [
      "Familia activa",
      "Espacio para jugar",
      "Compromiso de esterilización cuando tenga la edad adecuada",
      "Tiempo para entrenamiento básico",
    ],
    story:
      "Sasha fue encontrada junto a sus hermanos en una caja abandonada cerca de un río. Afortunadamente, un buen samaritano los rescató y los llevó a nuestra fundación. Es la más activa de la camada y siempre está lista para jugar y aprender cosas nuevas.",
    images: [
      "/patitas-unidas/assets/patita_2.jpg",
      "/patitas-unidas/assets/patita_2.jpg",
      "/patitas-unidas/assets/patita_2.jpg",
    ],
    createdAt: "2023-09-05",
    foundation: {
      id: 1,
      name: "Huellitas de Amor",
      logo: "/patitas-unidas/assets/huellitas_logo.jpg",
      city: "Bogotá",
      description:
        "Rescatamos y damos en adopción animales en situación de calle en Bogotá.",
      email: "contacto@huellitasdeamor.org",
      phone: "+57 300 123 4567",
    },
  },
  {
    id: 3,
    name: "Drax",
    type: "Perro",
    state: "Urgente",
    tag: "Tranquilo",
    age: "Cachorro",
    description:
      "Tranquila y mimosa, busca un hogar donde pueda recibir mucho amor.",
    image: "/patitas-unidas/assets/patita_3.jpg",
    fundacionId: 3,
    breed: "Pitbull mezclado",
    gender: "Macho",
    size: "Mediano (en crecimiento)",
    color: "Atigrado",
    personality: ["Tranquilo", "Cariñoso", "Leal", "Inteligente"],
    healthStatus: "Bueno",
    vaccinated: true,
    sterilized: false,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Perros", "Adultos"],
    notGoodWith: ["Gatos"],
    adoptionRequirements: [
      "Experiencia con la raza",
      "Hogar sin otros animales pequeños",
      "Compromiso de entrenamiento y socialización",
      "Compromiso de esterilización",
    ],
    story:
      "Drax fue rescatado de una situación de maltrato cuando tenía apenas 2 meses. A pesar de su difícil comienzo, es un cachorro extremadamente dulce y tranquilo que adora a las personas. Necesita un hogar paciente que le ayude a superar sus miedos y le enseñe que el mundo puede ser un lugar seguro.",
    images: [
      "/patitas-unidas/assets/patita_3.jpg",
      "/patitas-unidas/assets/patita_3.jpg",
      "/patitas-unidas/assets/patita_3.jpg",
    ],
    createdAt: "2023-07-20",
    foundation: {
      id: 3,
      name: "Amigos Peludos",
      logo: "/patitas-unidas/assets/amigos_peludos_logo.jpg",
      city: "Cali",
      description:
        "Organización dedicada al rescate y rehabilitación de perros en situación de calle y maltrato en Cali.",
      email: "contacto@amigospeludos.org",
      phone: "+57 322 789 0123",
    },
  },
  {
    id: 4,
    name: "Tobhias",
    type: "Perro",
    state: "Urgente",
    tag: "Tranquilo",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_4.jpg",
    fundacionId: 1,
    breed: "Pastor Alemán mezclado",
    gender: "Macho",
    size: "Grande",
    color: "Negro y marrón",
    personality: ["Tranquilo", "Protector", "Inteligente", "Leal"],
    healthStatus: "Bueno",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Perros", "Niños mayores", "Adultos"],
    notGoodWith: ["Gatos", "Animales pequeños"],
    adoptionRequirements: [
      "Hogar con espacio amplio",
      "Experiencia con perros grandes",
      "Familia activa",
      "Tiempo para paseos diarios",
    ],
    story:
      "Tobhias fue entregado a nuestra fundación cuando su familia anterior tuvo que mudarse a un apartamento donde no permitían mascotas. Es un perro muy bien educado y tranquilo que ha vivido con una familia durante 3 años. Es excelente con niños mayores y muy protector con su familia.",
    images: [
      "/patitas-unidas/assets/patita_4.jpg",
      "/patitas-unidas/assets/patita_4.jpg",
      "/patitas-unidas/assets/patita_4.jpg",
    ],
    createdAt: "2023-06-12",
    foundation: {
      id: 1,
      name: "Huellitas de Amor",
      logo: "/patitas-unidas/assets/huellitas_logo.jpg",
      city: "Bogotá",
      description:
        "Rescatamos y damos en adopción animales en situación de calle en Bogotá.",
      email: "contacto@huellitasdeamor.org",
      phone: "+57 300 123 4567",
    },
  },
  {
    id: 5,
    name: "Blanca nieves",
    type: "Gato",
    state: "Nuevo",
    tag: "Independiente",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_5.jpg",
    fundacionId: 2,
    breed: "Angora mezclado",
    gender: "Hembra",
    size: "Mediano",
    color: "Blanco",
    personality: ["Independiente", "Elegante", "Tranquila", "Selectiva"],
    healthStatus: "Excelente",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Adultos", "Hogares tranquilos"],
    notGoodWith: ["Perros", "Niños pequeños", "Ambientes ruidosos"],
    adoptionRequirements: [
      "Hogar tranquilo",
      "Experiencia con gatos",
      "Sin niños pequeños",
      "Sin otros animales",
    ],
    story:
      "Blanca Nieves fue rescatada de la calle cuando era adulta. Es una gata muy elegante y limpia que disfruta de la tranquilidad. Prefiere observar desde la distancia antes de acercarse, pero una vez que confía en ti, es muy cariñosa a su manera. Busca un hogar tranquilo donde pueda ser la reina de la casa.",
    images: [
      "/patitas-unidas/assets/patita_5.jpg",
      "/patitas-unidas/assets/patita_5.jpg",
      "/patitas-unidas/assets/patita_5.jpg",
    ],
    createdAt: "2023-09-18",
    foundation: {
      id: 2,
      name: "Patitas Felices",
      logo: "/patitas-unidas/assets/patitas_felices_logo.jpg",
      city: "Medellín",
      description:
        "Fundación dedicada al rescate y rehabilitación de gatos callejeros en Medellín.",
      email: "info@patitasfelices.org",
      phone: "+57 311 456 7890",
    },
  },
  {
    id: 7,
    name: "Nina",
    type: "Gato",
    state: "Tranquilo",
    age: "Cachorro",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_7.jpg",
    fundacionId: 3,
    breed: "Doméstico de pelo corto",
    gender: "Hembra",
    size: "Pequeño",
    color: "Atigrado gris",
    personality: ["Tranquila", "Juguetona", "Curiosa", "Cariñosa"],
    healthStatus: "Excelente",
    vaccinated: true,
    sterilized: false,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Gatos", "Perros tranquilos", "Niños", "Adultos"],
    notGoodWith: [],
    adoptionRequirements: [
      "Compromiso de esterilización cuando tenga la edad adecuada",
      "Hogar seguro para gatos",
      "Tiempo para jugar y socializar",
    ],
    story:
      "Nina fue encontrada junto a sus hermanos en un terreno baldío. Es la más tranquila de la camada, pero no por ello menos juguetona. Le encanta explorar y descubrir nuevos lugares, siempre con mucha cautela. Es muy sociable con otros gatos y se adapta fácilmente a nuevos ambientes.",
    images: [
      "/patitas-unidas/assets/patita_7.jpg",
      "/patitas-unidas/assets/patita_7.jpg",
      "/patitas-unidas/assets/patita_7.jpg",
    ],
    createdAt: "2023-08-30",
    foundation: {
      id: 3,
      name: "Amigos Peludos",
      logo: "/patitas-unidas/assets/amigos_peludos_logo.jpg",
      city: "Cali",
      description:
        "Organización dedicada al rescate y rehabilitación de perros en situación de calle y maltrato en Cali.",
      email: "contacto@amigospeludos.org",
      phone: "+57 322 789 0123",
    },
  },
  {
    id: 8,
    name: "Blue",
    type: "Gato",
    state: "Juguetón",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_8.jpg",
    fundacionId: 2,
    breed: "Ruso Azul mezclado",
    gender: "Macho",
    size: "Mediano",
    color: "Gris azulado",
    personality: ["Juguetón", "Activo", "Inteligente", "Curioso"],
    healthStatus: "Excelente",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Gatos", "Adultos", "Niños mayores"],
    notGoodWith: ["Perros"],
    adoptionRequirements: [
      "Hogar con espacio para jugar",
      "Juguetes interactivos",
      "Tiempo para jugar diariamente",
      "Experiencia con gatos activos",
    ],
    story:
      "Blue fue rescatado de la calle cuando tenía aproximadamente un año. Es extremadamente juguetón y activo, siempre buscando nuevas aventuras. Le encanta trepar y explorar cada rincón de la casa. Necesita un hogar que pueda proporcionarle suficiente estimulación mental y física para mantenerlo feliz.",
    images: [
      "/patitas-unidas/assets/patita_8.jpg",
      "/patitas-unidas/assets/patita_8.jpg",
      "/patitas-unidas/assets/patita_8.jpg",
    ],
    createdAt: "2023-07-05",
    foundation: {
      id: 2,
      name: "Patitas Felices",
      logo: "/patitas-unidas/assets/patitas_felices_logo.jpg",
      city: "Medellín",
      description:
        "Fundación dedicada al rescate y rehabilitación de gatos callejeros en Medellín.",
      email: "info@patitasfelices.org",
      phone: "+57 311 456 7890",
    },
  },
  {
    id: 9,
    name: "Pelusa",
    type: "Perro",
    state: "Urgente",
    tag: "Juguetón",
    age: "Adulto",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_9.jpg",
    fundacionId: 1,
    breed: "Poodle mezclado",
    gender: "Macho",
    size: "Pequeño",
    color: "Blanco",
    personality: ["Juguetón", "Cariñoso", "Sociable", "Enérgico"],
    healthStatus: "Bueno",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Perros", "Gatos", "Niños", "Adultos"],
    notGoodWith: [],
    adoptionRequirements: [
      "Tiempo para paseos diarios",
      "Cepillado regular",
      "Familia activa",
      "Hogar donde no esté solo por largos periodos",
    ],
    story:
      "Pelusa fue entregado a nuestra fundación cuando su dueño anterior falleció. Es un perro muy sociable que ha vivido con otros perros y gatos. Le encanta jugar y recibir atención. Está acostumbrado a la vida en familia y se adapta fácilmente a nuevos entornos. Busca un hogar donde pueda seguir siendo parte de la familia.",
    images: [
      "/patitas-unidas/assets/patita_9.jpg",
      "/patitas-unidas/assets/patita_9.jpg",
      "/patitas-unidas/assets/patita_9.jpg",
    ],
    createdAt: "2023-06-28",
    foundation: {
      id: 1,
      name: "Huellitas de Amor",
      logo: "/patitas-unidas/assets/huellitas_logo.jpg",
      city: "Bogotá",
      description:
        "Rescatamos y damos en adopción animales en situación de calle en Bogotá.",
      email: "contacto@huellitasdeamor.org",
      phone: "+57 300 123 4567",
    },
  },
  { 
    id: 6,
    name: "Francheska",
    type: "Gato",
    state: "Urgente",
    tag: "Independiente",
    age: "Cachorro",
    description: "Juguetón y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/patita_6.jpg",
    fundacionId: 3,
    breed: "Doméstico de pelo largo",
    gender: "Hembra",
    size: "Pequeño",
    color: "Tricolor",
    personality: ["Independiente", "Juguetona", "Observadora", "Inteligente"],
    healthStatus: "Bueno",
    vaccinated: true,
    sterilized: false,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Gatos", "Adultos tranquilos"],
    notGoodWith: ["Perros grandes", "Niños pequeños"],
    adoptionRequirements: [
      "Hogar tranquilo",
      "Compromiso de esterilización",
      "Experiencia con gatos",
      "Paciencia para socialización",
    ],
    story:
      "Francheska fue rescatada de la calle cuando tenía apenas unas semanas. A pesar de ser muy pequeña, muestra una personalidad independiente y observadora. Le gusta jugar, pero también disfruta de sus momentos de soledad. Necesita un hogar paciente que respete su espacio y le dé tiempo para adaptarse.",
    images: [
      "/patitas-unidas/assets/patita_6.jpg",
      "/patitas-unidas/assets/patita_6.jpg",
      "/patitas-unidas/assets/patita_6.jpg",
    ],
    createdAt: "2023-09-02",
    foundation: {
      id: 3,
      name: "Amigos Peludos",
      logo: "/patitas-unidas/assets/amigos_peludos_logo.jpg",
      city: "Cali",
      description:
        "Organización dedicada al rescate y rehabilitación de perros en situación de calle y maltrato en Cali.",
      email: "contacto@amigospeludos.org",
      phone: "+57 322 789 0123",
    },
  },
  {
    id: 11,
    name: "Tyson",
    type: "Perro",
    state: "No adopción",
    tag: "Lindo",
    age: "Adulto",
    description:
      "Perro lindo y cariñoso, le encanta correr y jugar con pelotas.",
    image: "/patitas-unidas/assets/tyson.jpg",
    fundacionId: 2,
    breed: "Bulldog Francés",
    gender: "Macho",
    size: "Pequeño",
    color: "Atigrado",
    personality: ["Lindo", "Cariñoso", "Juguetón", "Tranquilo"],
    healthStatus: "Excelente",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: false,
    goodWith: ["Perros", "Gatos", "Niños", "Adultos"],
    notGoodWith: [],
    adoptionRequirements: [
      "No disponible para adopción - Mascota de la fundación",
      "Puedes visitarlo en nuestras instalaciones",
    ],
    story:
      "Tyson es la mascota oficial de nuestra fundación. Fue rescatado hace 3 años de una situación de maltrato y, debido a su increíble personalidad y capacidad para socializar con otros animales, decidimos que sería nuestro embajador. Ayuda a los nuevos rescatados a adaptarse y es la estrella de nuestros eventos de adopción. No está disponible para adopción, pero puedes visitarlo cuando quieras.",
    images: [
      "/patitas-unidas/assets/tyson.jpg",
      "/patitas-unidas/assets/tyson.jpg",
      "/patitas-unidas/assets/tyson.jpg",
    ],
    createdAt: "2020-05-10",
    foundation: {
      id: 2,
      name: "Patitas Felices",
      logo: "/patitas-unidas/assets/patitas_felices_logo.jpg",
      city: "Medellín",
      description:
        "Fundación dedicada al rescate y rehabilitación de gatos callejeros en Medellín.",
      email: "info@patitasfelices.org",
      phone: "+57 311 456 7890",
    },
  },
  // Animales de apadrinamiento
  {
    id: 101,
    name: "Luna",
    type: "Gato",
    age: "Adulto",
    description: "Requiere cirugía y cuidados post-operatorios.",
    image: "/assets/patita_apadrina_1.jpg",
    state: "Necesita ayuda",
    tag: "Especial",
    fundacionId: 1,
    breed: "Doméstico de pelo corto",
    gender: "Hembra",
    size: "Mediano",
    color: "Negro con blanco",
    personality: ["Tranquila", "Cariñosa", "Resiliente"],
    healthStatus: "Requiere atención",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: true,
    goodWith: ["Gatos", "Adultos tranquilos"],
    notGoodWith: ["Perros", "Ambientes ruidosos"],
    adoptionRequirements: [
      "No disponible para adopción - Solo apadrinamiento",
      "Posibilidad de visitas periódicas",
    ],
    story:
      "Luna fue rescatada después de un accidente que le causó una fractura en la cadera. Necesita una cirugía costosa y rehabilitación posterior. Es una gata muy dulce que, a pesar del dolor, siempre recibe a todos con ronroneos. Tu apadrinamiento ayudará a cubrir los gastos de su cirugía y recuperación.",
    images: [
      "/assets/patita_apadrina_1.jpg",
      "/assets/patita_apadrina_1.jpg",
      "/assets/patita_apadrina_1.jpg",
    ],
    createdAt: "2023-08-15",
    foundation: {
      id: 1,
      name: "Huellitas de Amor",
      logo: "/patitas-unidas/assets/huellitas_logo.jpg",
      city: "Bogotá",
      description:
        "Rescatamos y damos en adopción animales en situación de calle en Bogotá.",
      email: "contacto@huellitasdeamor.org",
      phone: "+57 300 123 4567",
    },
  },
  {
    id: 102,
    name: "Max",
    type: "Perro",
    age: "Cachorro",
    description: "Necesita tratamiento médico y alimentación especial.",
    image: "/assets/patita_apadrina_2.jpg",
    state: "Necesita ayuda",
    tag: "Tratamiento",
    fundacionId: 2,
    breed: "Mestizo",
    gender: "Macho",
    size: "Pequeño (en crecimiento)",
    color: "Marrón",
    personality: ["Juguetón", "Valiente", "Cariñoso"],
    healthStatus: "En tratamiento",
    vaccinated: true,
    sterilized: false,
    dewormed: true,
    specialNeeds: true,
    goodWith: ["Perros", "Gatos", "Niños", "Adultos"],
    notGoodWith: [],
    adoptionRequirements: [
      "No disponible para adopción inmediata - Solo apadrinamiento",
      "Posibilidad de adopción futura cuando se recupere",
    ],
    story:
      "Max fue encontrado muy desnutrido y con una infección severa. Actualmente está en tratamiento y necesita medicación diaria y una alimentación especial para recuperarse completamente. A pesar de su condición, es un cachorro muy alegre y juguetón. Tu apadrinamiento ayudará a cubrir sus gastos médicos y alimentación especial.",
    images: [
      "/assets/patita_apadrina_2.jpg",
      "/assets/patita_apadrina_2.jpg",
      "/assets/patita_apadrina_2.jpg",
    ],
    createdAt: "2023-09-05",
    foundation: {
      id: 2,
      name: "Patitas Felices",
      logo: "/patitas-unidas/assets/patitas_felices_logo.jpg",
      city: "Medellín",
      description:
        "Fundación dedicada al rescate y rehabilitación de gatos callejeros en Medellín.",
      email: "info@patitasfelices.org",
      phone: "+57 311 456 7890",
    },
  },
  {
    id: 103,
    name: "Milo",
    type: "Gato",
    age: "Adulto",
    description: "Requiere medicación diaria para su recuperación.",
    image: "/assets/patita_apadrina_3.jpg",
    state: "Necesita ayuda",
    tag: "Medicamentos",
    fundacionId: 3,
    breed: "Doméstico de pelo largo",
    gender: "Macho",
    size: "Mediano",
    color: "Naranja",
    personality: ["Tranquilo", "Cariñoso", "Paciente"],
    healthStatus: "Crónico estable",
    vaccinated: true,
    sterilized: true,
    dewormed: true,
    specialNeeds: true,
    goodWith: ["Gatos", "Adultos", "Ambientes tranquilos"],
    notGoodWith: ["Perros", "Niños pequeños"],
    adoptionRequirements: [
      "No disponible para adopción - Solo apadrinamiento",
      "Compromiso de medicación de por vida",
    ],
    story:
      "Milo fue diagnosticado con una enfermedad renal crónica que requiere medicación diaria y una dieta especial. A pesar de su condición, es un gato muy dulce y tranquilo que disfruta de la compañía humana. Tu apadrinamiento ayudará a cubrir sus medicamentos mensuales y alimento especial para mantener su calidad de vida.",
    images: [
      "/assets/patita_apadrina_3.jpg",
      "/assets/patita_apadrina_3.jpg",
      "/assets/patita_apadrina_3.jpg",
    ],
    createdAt: "2023-07-10",
    foundation: {
      id: 3,
      name: "Amigos Peludos",
      logo: "/patitas-unidas/assets/amigos_peludos_logo.jpg",
      city: "Cali",
      description:
        "Organización dedicada al rescate y rehabilitación de perros en situación de calle y maltrato en Cali.",
      email: "contacto@amigospeludos.org",
      phone: "+57 322 789 0123",
    },
  },
  {
    id: 104,
    name: "Nina",
    type: "Perro",
    age: "Cachorro",
    description: "Recuperándose de una fractura, necesita fisioterapia.",
    image: "/assets/patita_apadrina_4.jpg",
    state: "Necesita ayuda",
    tag: "Fisioterapia",
    fundacionId: 1,
    breed: "Border Collie mezclado",
    gender: "Hembra",
    size: "Mediano (en crecimiento)",
    color: "Blanco y negro",
    personality: ["Valiente", "Inteligente", "Determinada"],
    healthStatus: "En recuperación",
    vaccinated: true,
    sterilized: false,
    dewormed: true,
    specialNeeds: true,
    goodWith: ["Perros", "Gatos", "Niños", "Adultos"],
    notGoodWith: [],
    adoptionRequirements: [
      "No disponible para adopción inmediata - Solo apadrinamiento",
      "Posibilidad de adopción futura cuando se recupere completamente",
    ],
    story:
      "Nina sufrió un accidente que le causó una fractura en una de sus patas traseras. Ha sido operada con éxito, pero necesita sesiones de fisioterapia para recuperar completamente la movilidad. Es una cachorra muy inteligente y determinada que está poniendo todo de su parte para recuperarse. Tu apadrinamiento ayudará a cubrir sus sesiones de fisioterapia y medicamentos.",
    images: [
      "/assets/patita_apadrina_4.jpg",
      "/assets/patita_apadrina_4.jpg",
      "/assets/patita_apadrina_4.jpg",
    ],
    createdAt: "2023-08-25",
    foundation: {
      id: 1,
      name: "Huellitas de Amor",
      logo: "/patitas-unidas/assets/huellitas_logo.jpg",
      city: "Bogotá",
      description:
        "Rescatamos y damos en adopción animales en situación de calle en Bogotá.",
      email: "contacto@huellitasdeamor.org",
      phone: "+57 300 123 4567",
    },
  },
];

export const animalService = {
  getAnimales: async (): Promise<Animal[]> => {
    // Simula una llamada a API con un pequeño retardo
    return new Promise((resolve) => {
      setTimeout(() => resolve(ANIMALES), 500);
    });
  },
  getApadrinables: async (): Promise<Animal[]> => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(ANIMALES_APADRINAMIENTO), 500);
    });
  },
  getAnimalesPorFundacion: async (fundacionId: number): Promise<Animal[]> => {
    return new Promise((resolve) => {
      setTimeout(
        () => resolve(ANIMALES.filter((a) => a.fundacionId === fundacionId)),
        500
      );
    });
  },

  /**
   * Retrieves a list of all animals with their detailed information.
   * @returns {Promise<AnimalData[]>} A promise that resolves to an array of AnimalData objects.
   * @note Currently using mock data with a 500ms delay
   */
  getAnimals: async (): Promise<AnimalData[]> => {
    return new Promise((resolve) => {
      setTimeout(() => resolve(AnimalsData), 500);
    });
  },

  /**
   * Retrieves detailed information for a specific animal by ID.
   * @param {number} animalId - The unique identifier of the animal
   * @returns {Promise<AnimalData>} A promise that resolves to the animal's detailed data
   * @throws {Error} If the animal is not found
   * @note Currently using mock data with a 500ms delay
   */
  getAnimalData: async (animalId: number): Promise<AnimalData> => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        const animal = AnimalsData.find((a) => a.id === animalId);
        if (!animal) {
          reject(new Error("Animal not found"));
        }
        resolve(animal!);
      }, 500);
    });
  },
};
