<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PatitasUnidas.Domain\PatitasUnidas.Domain.csproj" />
    <ProjectReference Include="..\PatitasUnidas.Application\PatitasUnidas.Application.csproj" />
  </ItemGroup>

</Project>
